Update and rename format-code.yml to format-and-verify-code.yml

diff --git a/.github/workflows/format-and-verify-code.yml b/.github/workflows/format-and-verify-code.yml
--- a/.github/workflows/format-and-verify-code.yml
+++ b/.github/workflows/format-and-verify-code.yml
@@ -1,4 +1,4 @@
-name: format-code
+name: format-and-verify-code
 
 on:
   pull_request:
@@ -7,50 +7,48 @@ on:
 
 jobs:
   format-code:
-    # Skip this job if the actor is the GitHub Actions bot
-    if: github.actor != 'github-actions[bot]'
     runs-on: ubuntu-latest
-
     permissions:
       contents: write
       pull-requests: write
-      checks: write
-
     steps:
       - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
-
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.11'
-
       - name: Install pre-commit
-        run: |
-          python -m pip install --upgrade pip
-          pip install pre-commit
-
+        run: pip install pre-commit
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "1.9.4"
-
       - name: Copy pre-commit config
         run: |
           mkdir -p .github/workflows
           curl -O https://raw.githubusercontent.com/oslokommune-reg/.github/prod/.github/workflows/config/.pre-commit-config.yaml
-
-      - name: Run pre-commit on changed files
-        run: |
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-            git fetch origin ${{ github.base_ref }}
-            pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD
-          else
-            pre-commit run --all-files
-          fi
-        continue-on-error: true
-
+      - name: Run pre-commit
+        run: pre-commit run --all-files
       - uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: "Applied formatting"
+
+  verify-formatting:
+    needs: format-code
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.11'
+      - name: Install pre-commit
+        run: pip install pre-commit
+      - name: Run pre-commit
+        run: pre-commit run --all-files
+      - name: Check for unstaged changes
+        run: |
+          if ! git diff --exit-code; then
+            echo "Formatting check failed. Please close and reopen the pull request to trigger new."
+            exit 1
+          fi
